/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>

#include "ShortcutCreator.h"

#include <objbase.h>
#include <winerror.h>
#include "shobjidl.h"
#include "objidl.h"
#include "shlguid.h"
#include "ComPtr.h"

#pragma comment(lib, "Ole32.lib")

class CCoInitialize {
public:
 CCoInitialize() : m_hr(CoInitialize(NULL)) { }
 ~CCoInitialize() { if (SUCCEEDED(m_hr)) CoUninitialize(); }
 operator HRESULT() const { return m_hr; }
 HRESULT m_hr;
};

int main () {
    CCoInitialize init;

    if(FAILED(init)) {
        return -1;
    }

    ShortcutCreator shortcutCreator;

    if (FAILED(shortcutCreator)) {
        return -1;
    }





    return 0;
}
