#!/usr/bin/env bash
SCRIPT_PATH="$(dirname "$(realpath -s "$BASH_SOURCE[0]")")"
SANDBOX_PATH="$(realpath "$(find "$SCRIPT_PATH/../vscode" -type f -name chrome-sandbox)")"
CODE_PATH="$(realpath "$(find "$SCRIPT_PATH/../vscode" -type f -name code | grep bin)")"

if [ "$(sysctl -n kernel.apparmor_restrict_unprivileged_userns)" -eq "0" ] || [ "$(stat -c "%U" "$SANDBOX_PATH")" == "root" ] || [ -f "/etc/apparmor.d/frccode" ]; then
	"$CODE_PATH" $@
else
        "$CODE_PATH" --no-sandbox $@
fi
