name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '13 12 * * *'

jobs:
  nightly:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact-name: Linux
            build-options: "-PlinuxBuild"
          - os: macos-latest
            artifact-name: macOS
            build-options: "-PmacBuild"
          - os: windows-latest
            artifact-name: Win64
            build-options: ""

    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x' 

      - name: Setup Development Artifacts
        shell: bash
        run: ./automation/nightly_setup.sh

      - name: Build Installer
        shell: bash
        run: ./gradlew generateInstallers -PjenkinsBuild ${{ matrix.build-options }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-name }}
          path: build/pubOutputs/ 
